1 FÖRSTA GÅNGEN npm install I MAPPEN ANVÄND cd "TWITCHBOT MAPPEN" sen npm install MED POWERSHELL ELLER CMD
2 MODIFIERA  PROXY IN I TOPPEN AV INDEX.JS
let proxyobj = {
    ip: '161.123.31.149',
    port: '36246',
    username: 'proxyfish290',
    password: 'hnbfrxth',
}
3 SKRIV node signup.js MED POWERSHELL ELLER CMD I TWITCHBOT MAPPEN
4 VÄNTA PÅ POTENTIEL CAPATCHA
5 STARTA OM 
6 RAMLA INTE MED CYKEL
7 GÅ TILL STEG 1
